
import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Iphone16(),
        ]),
      ),
    );
  }
}

class Iphone16 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 13,
                top: 19,
                child: Container(
                  width: 49,
                  height: 49,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/images/pfp1.jpeg"),
                      fit: BoxFit.cover,
                    ),
                    shape: OvalBorder(side: BorderSide(width: 1)),
                  ),
                ),
              ),
              Positioned(
                left: 13,
                top: 238,
                child: Container(
                  width: 49,
                  height: 49,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF054AB0),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 284,
                top: 19,
                child: Container(
                  width: 49,
                  height: 49,
                  decoration: ShapeDecoration(
                    color: Colors.black,
                    shape: OvalBorder(side: BorderSide(width: 1)),
                  ),
                ),
              ),
              Positioned(
                left: 333,
                top: 19,
                child: Container(
                  width: 49,
                  height: 49,
                  decoration: ShapeDecoration(
                    color: Colors.black,
                    shape: OvalBorder(side: BorderSide(width: 1)),
                  ),
                ),
              ),
              Positioned(
                left: 12,
                top: 344,
                child: Container(
                  width: 369,
                  height: 496,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(20),
                        bottomRight: Radius.circular(20),
                      ),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 60,
                        top: 201,
                        child: Container(
                          width: 9,
                          height: 9,
                          decoration: BoxDecoration(color: const Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 65,
                        top: 151,
                        child: Container(
                          width: 114,
                          height: 86,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF6F6F6),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(15),
                                topRight: Radius.circular(15),
                                bottomLeft: Radius.circular(25),
                                bottomRight: Radius.circular(25),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 179,
                          height: 206,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: AssetImage("assets/images/sepatu1.png"),
                              fit: BoxFit.cover,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(15),
                                topRight: Radius.circular(15),
                                bottomLeft: Radius.circular(20),
                                bottomRight: Radius.circular(15),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1,
                        top: 206,
                        child: Container(
                          width: 74,
                          height: 26,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(15),
                                topRight: Radius.circular(15),
                                bottomLeft: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 35,
                        top: 216,
                        child: SizedBox(
                          width: 42,
                          height: 16,
                          child: Text(
                            '4.5',
                            style: TextStyle(
                              color: const Color(0xFF949494),
                              fontSize: 15,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 14,
                        top: 220,
                        child: Container(
                          width: 17,
                          height: 17,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 247,
                        child: SizedBox(
                          width: 145,
                          height: 24,
                          child: Text(
                            'Nike SB Dunk Low',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w500,
                              height: 1.12,
                              letterSpacing: -0.64,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 271,
                        child: SizedBox(
                          width: 145,
                          height: 24,
                          child: Text(
                            'Rp. 1.900.000',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 1.12,
                              letterSpacing: -0.64,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 119,
                        top: 11,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFDBDBDB),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 131,
                        top: 23,
                        child: Container(
                          width: 20,
                          height: 20,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                        ),
                      ),
                      Positioned(
                        left: 250,
                        top: 504,
                        child: Container(
                          width: 9,
                          height: 9,
                          decoration: BoxDecoration(color: const Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 255,
                        top: 454,
                        child: Container(
                          width: 114,
                          height: 86,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF6F6F6),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(15),
                                topRight: Radius.circular(15),
                                bottomLeft: Radius.circular(25),
                                bottomRight: Radius.circular(25),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 190,
                        top: 303,
                        child: Container(
                          width: 179,
                          height: 206,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: AssetImage("assets/images/seaptu2.png"),
                              fit: BoxFit.cover,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(15),
                                topRight: Radius.circular(15),
                                bottomLeft: Radius.circular(20),
                                bottomRight: Radius.circular(15),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 191,
                        top: 509,
                        child: Container(
                          width: 74,
                          height: 26,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(15),
                                topRight: Radius.circular(15),
                                bottomLeft: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 225,
                        top: 519,
                        child: SizedBox(
                          width: 42,
                          height: 16,
                          child: Text(
                            '4.5',
                            style: TextStyle(
                              color: const Color(0xFF949494),
                              fontSize: 15,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 204,
                        top: 523,
                        child: Container(
                          width: 17,
                          height: 17,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 190,
                        top: 550,
                        child: SizedBox(
                          width: 145,
                          height: 24,
                          child: Text(
                            'Nike SB Dunk Low',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w500,
                              height: 1.12,
                              letterSpacing: -0.64,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 190,
                        top: 574,
                        child: SizedBox(
                          width: 145,
                          height: 24,
                          child: Text(
                            'Rp. 1.900.000',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 1.12,
                              letterSpacing: -0.64,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 309,
                        top: 314,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFDBDBDB),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 321,
                        top: 326,
                        child: Container(
                          width: 20,
                          height: 20,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                        ),
                      ),
                      Positioned(
                        left: 250,
                        top: 201,
                        child: Container(
                          width: 9,
                          height: 9,
                          decoration: BoxDecoration(color: const Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 255,
                        top: 151,
                        child: Container(
                          width: 114,
                          height: 86,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF6F6F6),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(15),
                                topRight: Radius.circular(15),
                                bottomLeft: Radius.circular(25),
                                bottomRight: Radius.circular(25),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 190,
                        top: 0,
                        child: Container(
                          width: 179,
                          height: 206,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: AssetImage("assets/images/seaptu2.png"),
                              fit: BoxFit.cover,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(15),
                                topRight: Radius.circular(15),
                                bottomLeft: Radius.circular(20),
                                bottomRight: Radius.circular(15),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 191,
                        top: 206,
                        child: Container(
                          width: 74,
                          height: 26,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(15),
                                topRight: Radius.circular(15),
                                bottomLeft: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 310,
                        top: 11,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFDBDBDB),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 223,
                        top: 216,
                        child: SizedBox(
                          width: 42,
                          height: 16,
                          child: Text(
                            '4.5',
                            style: TextStyle(
                              color: const Color(0xFF949494),
                              fontSize: 15,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 202,
                        top: 220,
                        child: Container(
                          width: 17,
                          height: 17,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 190,
                        top: 247,
                        child: Text(
                          'Nike Air 180',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                            height: 1.12,
                            letterSpacing: -0.64,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 190,
                        top: 271,
                        child: SizedBox(
                          width: 145,
                          height: 24,
                          child: Text(
                            'Rp. 1.900.000',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 1.12,
                              letterSpacing: -0.64,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 322,
                        top: 22,
                        child: Container(
                          width: 25,
                          height: 25,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 60,
                        top: 504,
                        child: Container(
                          width: 9,
                          height: 9,
                          decoration: BoxDecoration(color: const Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 65,
                        top: 454,
                        child: Container(
                          width: 114,
                          height: 86,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF6F6F6),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(15),
                                topRight: Radius.circular(15),
                                bottomLeft: Radius.circular(25),
                                bottomRight: Radius.circular(25),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 303,
                        child: Container(
                          width: 179,
                          height: 206,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: AssetImage("assets/images/sepatu1.png"),
                              fit: BoxFit.cover,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(15),
                                topRight: Radius.circular(15),
                                bottomLeft: Radius.circular(20),
                                bottomRight: Radius.circular(15),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1,
                        top: 509,
                        child: Container(
                          width: 74,
                          height: 26,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(15),
                                topRight: Radius.circular(15),
                                bottomLeft: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 120,
                        top: 314,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFDBDBDB),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 33,
                        top: 519,
                        child: SizedBox(
                          width: 42,
                          height: 16,
                          child: Text(
                            '4.5',
                            style: TextStyle(
                              color: const Color(0xFF949494),
                              fontSize: 15,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 12,
                        top: 523,
                        child: Container(
                          width: 17,
                          height: 17,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 550,
                        child: Text(
                          'Nike Air 180',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                            height: 1.12,
                            letterSpacing: -0.64,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 574,
                        child: SizedBox(
                          width: 145,
                          height: 24,
                          child: Text(
                            'Rp. 1.900.000',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 1.12,
                              letterSpacing: -0.64,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 132,
                        top: 325,
                        child: Container(
                          width: 25,
                          height: 25,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 130,
                        top: 23,
                        child: Container(
                          width: 25,
                          height: 25,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 321,
                        top: 325,
                        child: Container(
                          width: 25,
                          height: 25,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 62,
                top: 19,
                child: Container(
                  width: 222,
                  height: 49,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1),
                      borderRadius: BorderRadius.circular(33),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 12,
                top: 91,
                child: Container(
                  width: 369,
                  height: 124,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/images/banner.png"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(23),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 62,
                top: 238,
                child: Container(
                  width: 320,
                  height: 49,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF054AB0),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(30),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 10,
                top: 312,
                child: SizedBox(
                  width: 111,
                  height: 24,
                  child: Text(
                    'Most Popular',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.12,
                      letterSpacing: -0.64,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 297,
                top: 304,
                child: SizedBox(
                  width: 111,
                  height: 24,
                  child: Text(
                    'See All',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.12,
                      letterSpacing: -0.64,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 761,
                child: Container(
                  width: 138.92,
                  height: 54.84,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFA6F63A),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 5),
                      borderRadius: BorderRadius.circular(30),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 165.92,
                top: 761,
                child: Container(
                  width: 201.08,
                  height: 54.84,
                  decoration: ShapeDecoration(
                    color: Colors.black,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(30),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 55,
                top: 780,
                child: SizedBox(
                  width: 111,
                  height: 24,
                  child: Text(
                    'Home',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF054AB0),
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0.90,
                      letterSpacing: -0.80,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 170.49,
                top: 764.66,
                child: Container(
                  width: 63.98,
                  height: 47.53,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF474747),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(94),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 234.47,
                top: 764.66,
                child: Container(
                  width: 63.98,
                  height: 47.53,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF474747),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(94),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 298.45,
                top: 764.66,
                child: Container(
                  width: 63.98,
                  height: 47.53,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF474747),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(94),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 185,
                top: 771,
                child: Container(
                  width: 34,
                  height: 34,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 193,
                top: 744,
                child: Container(
                  width: 96,
                  height: 96,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 20,
                top: 246,
                child: Container(
                  width: 35,
                  height: 35,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 78,
                top: 253,
                child: Container(
                  width: 286,
                  height: 20,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 18,
                        child: Container(
                          width: 28,
                          height: 2,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFA6F63A),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(14),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 54,
                          height: 18,
                          child: Text(
                            'Nike',
                            style: TextStyle(
                              color: const Color(0xFFA6F63A),
                              fontSize: 15,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w500,
                              height: 1.20,
                              letterSpacing: -0.60,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 54,
                        top: 0,
                        child: SizedBox(
                          width: 54,
                          height: 18,
                          child: Text(
                            'Adidas',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w300,
                              height: 1.20,
                              letterSpacing: -0.60,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 127,
                        top: 1,
                        child: SizedBox(
                          width: 54,
                          height: 18,
                          child: Text(
                            'Puma',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w300,
                              height: 1.20,
                              letterSpacing: -0.60,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 199,
                        top: 1,
                        child: SizedBox(
                          width: 92,
                          height: 18,
                          child: Text(
                            'NewBalance',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w300,
                              height: 1.20,
                              letterSpacing: -0.60,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 97,
                top: 35,
                child: SizedBox(
                  width: 111,
                  height: 24,
                  child: Text(
                    'Nike Dunk Low',
                    style: TextStyle(
                      color: const Color(0xFFC1C1C1),
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.12,
                      letterSpacing: -0.64,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}